#!/bin/bash
retries="10"
action="lock"
nullcmd="'which true'"
while getopts "lur:" opt; do
	case $opt in
		l) action="lock" ;;
		u) action="unlock" ;;
		r) action="$OPTARG" ;;
	esac
done
shift $((OPTIND - 1))
if [ $# -eq 0 ]; then
	cat >&2 <<EOF
	usage: $0 [ -l | -u ] [ -r retries ] LOCKFILE
EOF
	exit 1
fi
if [ -z "$(which lockfile | grep -v '^no')" ];then
	echo "$0 failed: lockfile utility not found in path" >&2
	exit 1
fi
if [ "$action" = "lock" ]; then
	if ! lockfile -1 -r $retries "$1" 2>/dev/null; then
		echo "$0 failed: could not lock the file in time" >&2
		exit 1
	fi
else
	if [ ! -f "$1" ]; then
		echo "$0: does not exit to lock"
		exit 1
	fi
	rm -f "$1"
fi
exit 0
